# Generated by Django 5.1.3 on 2025-04-23 11:59

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='blogs/images/')),
                ('author', models.CharField(default='Editor Team', max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('category', models.CharField(max_length=100)),
                ('tags', models.CharField(help_text='Separate tags with commas', max_length=200)),
                ('short_description', ckeditor.fields.RichTextField()),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='clients/')),
            ],
        ),
        migrations.CreateModel(
            name='HomeAbouts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='about/icons/')),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HomeFaq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.CharField(max_length=350)),
                ('ans', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('thumbnail', models.ImageField(upload_to='projects/thumbnails/')),
                ('banner_image', models.ImageField(upload_to='projects/banners/')),
                ('banner_image1', models.ImageField(blank=True, null=True, upload_to='projects/banners/')),
                ('banner_image2', models.ImageField(blank=True, null=True, upload_to='projects/banners/')),
                ('client', models.CharField(blank=True, max_length=100, null=True)),
                ('handler_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('starting_date', models.DateField(blank=True, null=True)),
                ('time_duration', models.CharField(max_length=100)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('projectoverview', ckeditor.fields.RichTextField()),
                ('report_analyis', ckeditor.fields.RichTextField()),
                ('result', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('thumbnail_image', models.ImageField(upload_to='services/thumbnails/')),
                ('icon_image', models.FileField(upload_to='services/icons/')),
                ('banner_image', models.FileField(upload_to='services/banners/')),
                ('title_main', models.CharField(max_length=200)),
                ('desc', ckeditor.fields.RichTextField()),
                ('title_2', models.CharField(blank=True, max_length=200, null=True)),
                ('desc_2', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('title_3', models.CharField(blank=True, max_length=200, null=True)),
                ('desc_3', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('title_4', models.CharField(blank=True, max_length=200, null=True)),
                ('desc_4', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='team/')),
                ('name', models.CharField(max_length=50)),
                ('prof', models.CharField(max_length=50)),
                ('fburl', models.URLField(blank=True, null=True)),
                ('linkdinurl', models.URLField(blank=True, null=True)),
                ('twitterurl', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='testimonials/')),
                ('name', models.CharField(max_length=50)),
                ('prof', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('message', ckeditor.fields.RichTextField()),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='bydos.blog')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', ckeditor.fields.RichTextField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='bydos.service')),
            ],
        ),
    ]
