# Generated by Django 5.1.3 on 2025-04-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bydos', '0003_contactform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
